=== randovania/open-prime-hunters-rando/src/open_prime_hunters_rando/files/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "configuration_id": {
            "type": "integer",
            "default": 0,
            "description": "Identifier of the seed. Used for calculating RNG."
        },
        "starting_items": {
            "type": "object",
            "properties": {
                "weapons": {
                    "type": "object",
                    "description": "Determines what weapons to start with. Power Beam currently cannot be shuffled, so it is always starting.",
                    "properties": {
                        "battlehammer": {
                            "type": "boolean"
                        },
                        "imperialist": {
                            "type": "boolean"
                        },
                        "judicator": {
                            "type": "boolean"
                        },
                        "magmaul": {
                            "type": "boolean"
                        },
                        "missile_launcher": {
                            "type": "boolean"
                        },
                        "shock_coil": {
                            "type": "boolean"
                        },
                        "volt_driver": {
                            "type": "boolean"
                        }
                    },
                    "default": {
                        "battlehammer": false,
                        "imperialist": false,
                        "judicator": false,
                        "magmaul": false,
                        "missile_launcher": false,
                        "shock_coil": false,
                        "volt_driver": false
                    }
                },
                "missiles": {
                    "type": "integer",
                    "description": "The number of missiles to start with.",
                    "default": 5,
                    "minimum": 0,
                    "maximum": 100
                },
                "ammo": {
                    "type": "integer",
                    "description": "The amount of UA to start with.",
                    "default": 40,
                    "minimum": 0,
                    "maximum": 100
                },
                "energy": {
                    "type": "integer",
                    "description": "The amount of energy to start with.",
                    "default": 99,
                    "minimum": 1,
                    "maximum": 1299
                },
                "artifacts": {
                    "type": "object",
                    "description": "The amount of Artifacts to start with for each Boss Portal.",
                    "properties": {
                        "alinos_1": {
                            "type": "string"
                        },
                        "alinos_2": {
                            "type": "string"
                        },
                        "celestial_archives_1": {
                            "type": "string"
                        },
                        "celestial_archives_2": {
                            "type": "string"
                        },
                        "vesper_defense_outpost_1": {
                            "type": "string"
                        },
                        "vesper_defense_outpost_2": {
                            "type": "string"
                        },
                        "arcterra_1": {
                            "type": "string"
                        },
                        "arcterra_2": {
                            "type": "string"
                        }
                    },
                    "default": {
                        "alinos_1": "000",
                        "alinos_2": "000",
                        "celestial_archives_1": "000",
                        "celestial_archives_2": "000",
                        "vesper_defense_outpost_1": "000",
                        "vesper_defense_outpost_2": "000",
                        "arcterra_1": "000",
                        "arcterra_2": "000"
                    }
                },
                "octoliths": {
                    "type": "string",
                    "description": "Bitfield that determines what Octoliths to start with in descending order, 8-1.\nLeft to Right: Arcterra 2-1, VDO 2-1, Alinos 2-1, Celestial Archives 2-1",
                    "minLength": 8,
                    "default": "00000000"
                },
                "state_bits": {
                    "type": "array",
                    "description": "Determines which state bits are set by default.",
                    "default": [],
                    "items": {
                        "type": "number",
                        "minimum": 32,
                        "maximum": 64
                    }
                }
            },
            "required": [
                "weapons",
                "missiles"
            ]
        },
        "areas": {
            "type": "object",
            "properties": {
                "Celestial Archives": {
                    "$ref": "#/$defs/area"
                },
                "Alinos": {
                    "$ref": "#/$defs/area"
                },
                "Arcterra": {
                    "$ref": "#/$defs/area"
                },
                "Vesper Defense Outpost": {
                    "$ref": "#/$defs/area"
                },
                "Oubliette": {
                    "$ref": "#/$defs/area"
                }
            },
            "default": {},
            "additionalProperties": false
        },
        "ammo_sizes": {
            "type": "object",
            "description": "Configure the amount of ammo given by different sources.",
            "properties": {
                "missile_launcher": {
                    "type": "integer",
                    "default": 5,
                    "minimum": 0,
                    "maximum": 255
                },
                "missile_expansion": {
                    "type": "integer",
                    "default": 10,
                    "minimum": 0,
                    "maximum": 100
                },
                "ua_expansion": {
                    "type": "integer",
                    "default": 30,
                    "minimum": 0,
                    "maximum": 100
                }
            },
            "default": {}
        },
        "refill_sizes": {
            "type": "object",
            "description": "Configure the amount of ammo recovered by different sources.",
            "properties": {
                "small_energy": {
                    "type": "integer",
                    "default": 30,
                    "minimum": 0,
                    "maximum": 255
                },
                "medium_energy": {
                    "type": "integer",
                    "default": 60,
                    "minimum": 0,
                    "maximum": 255
                },
                "large_energy": {
                    "type": "integer",
                    "default": 100,
                    "minimum": 0,
                    "maximum": 255
                },
                "small_ammo": {
                    "type": "integer",
                    "default": 10,
                    "minimum": 0,
                    "maximum": 255
                },
                "large_ammo": {
                    "type": "integer",
                    "default": 25,
                    "minimum": 0,
                    "maximum": 255
                }
            },
            "default": {
                "small_energy": 30,
                "medium_energy": 60,
                "large_energy": 100,
                "small_ammo": 10,
                "large_ammo": 25
            }
        },
        "cosmetic_patches": {
            "type": "object",
            "properties": {
                "shuffle_hunter_colors": {
                    "type": "boolean",
                    "description": "Changes the colors of the hunters.",
                    "default": false
                },
                "suit_color": {
                    "type": "string",
                    "description": "Changes the palette used for Samus' suit",
                    "enum": [
                        "varia",
                        "purple",
                        "blue",
                        "black",
                        "orange",
                        "green"
                    ],
                    "default": "varia"
                },
                "randomize_light_source_colors": {
                    "type": "boolean",
                    "description": "If enabled, randomizes the colors of all light sources in the game.",
                    "default": false
                }
            }
        },
        "game_patches": {
            "type": "object",
            "properties": {
                "shuffle_hunter_ids": {
                    "type": "boolean",
                    "description": "Changes the hunter spawns to be a different hunter.",
                    "default": false
                },
                "unlock_planets": {
                    "type": "object",
                    "description": "Choose which planets are unlocked from the start.",
                    "properties": {
                        "Alinos": {
                            "type": "boolean"
                        },
                        "Arcterra": {
                            "type": "boolean"
                        },
                        "Vesper Defense Outpost": {
                            "type": "boolean"
                        }
                    },
                    "default": {
                        "Alinos": true,
                        "Arcterra": true,
                        "Vesper Defense Outpost": true
                    }
                },
                "skip_planet_intros": {
                    "type": "boolean",
                    "description": "If enabled, disables the ship landing sequence for each planet.",
                    "default": false
                }
            },
            "default": {}
        },
        "text_patches": {
            "type": "object",
            "properties": {
                "frontend": {
                    "type": "object",
                    "description": "Modify the text of an entry in a frontend text file.",
                    "patternProperties": {
                        ".*": {
                            "type": "string"
                        }
                    }
                },
                "string_tables": {
                    "type": "object",
                    "properties": {
                        "scan_log": {
                            "type": "object",
                            "description": "Modify the text of an entry in ScanLog.bin.",
                            "patternProperties": {
                                ".*": {
                                    "type": "string"
                                }
                            }
                        },
                        "ship_in_space": {
                            "type": "object",
                            "description": "Modify the text of an entry in ShipInSpace.bin",
                            "patternProperties": {
                                ".*": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "default": {}
    },
    "required": [
        "starting_items",
        "areas"
    ],
    "$defs": {
        "area": {
            "type": "object",
            "properties": {
                "levels": {
                    "type": "object",
                    "patternProperties": {
                        ".*": {
                            "$ref": "#/$defs/level"
                        }
                    }
                }
            },
            "required": [
                "levels"
            ],
            "additionalProperties": false
        },
        "level": {
            "type": "object",
            "properties": {
                "pickups": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "entity_id": {
                                "type": "integer",
                                "description": "The id of the entity."
                            },
                            "entity_type": {
                                "type": "integer",
                                "enum": [
                                    4,
                                    17
                                ],
                                "description": "The entity type of the entity.\nItemSpawn: 4, Artifact: 17"
                            }
                        },
                        "required": [
                            "entity_id",
                            "entity_type"
                        ],
                        "if": {
                            "properties": {
                                "entity_type": {
                                    "const": 4
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "item_type": {
                                    "type": "integer",
                                    "description": "The item type to change the entity into.",
                                    "minimum": 0,
                                    "maximum": 22
                                }
                            },
                            "required": [
                                "item_type"
                            ],
                            "if": {
                                "properties": {
                                    "item_type": {
                                        "const": 19
                                    }
                                }
                            },
                            "then": {
                                "properties": {
                                    "state_bit": {
                                        "type": "integer",
                                        "description": "The state bit to activate when picked up.",
                                        "minimum": 0,
                                        "maximum": 63
                                    }
                                },
                                "required": [
                                    "state_bit"
                                ]
                            }
                        },
                        "else": {
                            "properties": {
                                "model_id": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 8,
                                    "description": "The id of the model to use for the artifact."
                                },
                                "artifact_id": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 7,
                                    "description": "The id of the artifact."
                                }
                            },
                            "required": [
                                "model_id",
                                "artifact_id"
                            ]
                        }
                    },
                    "default": []
                },
                "force_fields": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "entity_id": {
                                "type": "integer",
                                "description": "The id of the entity."
                            },
                            "type": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 9,
                                "description": "The type of force field. Sealed force fields can only be unlocked remotely.\nPower Beam, Volt Driver, Missile, Battlehammer, Imperialist, Judicator, Magmaul, Shock Coil, Omega Cannon, Sealed."
                            }
                        }
                    },
                    "required": [
                        "entity_id",
                        "weapon_type"
                    ],
                    "default": []
                },
                "portals": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "entity_id": {
                                "type": "integer",
                                "description": "The id of the entity."
                            },
                            "target_index": {
                                "type": "integer",
                                "description": "The load index of the target portal."
                            },
                            "active": {
                                "type": "boolean",
                                "description": "Determines if the portal is active by default."
                            },
                            "entity_file_name": {
                                "type": "string",
                                "description": "The entity file of the target portal."
                            }
                        }
                    },
                    "required": [
                        "entity_id",
                        "target_index",
                        "entity_file_name"
                    ],
                    "default": []
                },
                "doors": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "entity_id": {
                                "type": "integer",
                                "description": "The id of the entity."
                            },
                            "weapon_type": {
                                "type": "integer",
                                "description": "The weakness of door. Sealed doors can only be unlocked remotely.\nPower Beam, Volt Driver, Missile, Battlehammer, Imperialist, Judicator, Magmaul, Shock Coil, Omega Cannon, Sealed."
                            },
                            "locked": {
                                "type": "boolean",
                                "description": "Change if the door is locked or not. Must be set to True in order for the modified weakness to be active in game."
                            }
                        }
                    },
                    "required": [
                        "entity_id",
                        "weapon_type"
                    ],
                    "default": []
                }
            }
        }
    }
}

=== randovania/open-prime-hunters-rando/tests/test_files/starter_preset_patcher.json
{
    "$schema": "../../src/open_prime_hunters_rando/files/schema.json",
    "configuration_id": 206913146,
    "starting_items": {
        "weapons": {
            "battlehammer": false,
            "imperialist": false,
            "judicator": false,
            "magmaul": false,
            "missile_launcher": false,
            "shock_coil": false,
            "volt_driver": false
        },
        "missiles": 0,
        "ammo": 40,
        "energy": 99,
        "octoliths": "11110000",
        "artifacts": {
            "alinos_1": "000",
            "alinos_2": "000",
            "celestial_archives_1": "000",
            "celestial_archives_2": "000",
            "vesper_defense_outpost_1": "000",
            "vesper_defense_outpost_2": "000",
            "arcterra_1": "000",
            "arcterra_2": "000"
        }
    },
    "areas": {
        "Celestial Archives": {
            "levels": {
                "Biodefense Chamber A": {
                    "pickups": [
                        {
                            "entity_id": 8,
                            "entity_type": 17,
                            "model_id": 1,
                            "artifact_id": 1
                        }
                    ],
                    "force_fields": [],
                    "portals": []
                },
                "Biodefense Chamber B": {
                    "pickups": [
                        {
                            "entity_id": 2,
                            "entity_type": 17,
                            "model_id": 8,
                            "artifact_id": 0
                        }
                    ],
                    "force_fields": [],
                    "portals": []
                },
                "Helm Room": {
                    "pickups": [],
                    "force_fields": [],
                    "portals": []
                },
                "Meditation Room": {
                    "pickups": [],
                    "force_fields": [],
                    "portals": []
                },
                "Fan Room Alpha": {
                    "pickups": [],
                    "force_fields": [],
                    "portals": []
                },
                "Fan Room Beta": {
                    "pickups": [],
                    "force_fields": [],
                    "portals": []
                },
                "Synergy Core": {
                    "pickups": [
                        {
                            "entity_id": 3,
                            "entity_type": 4,
                            "item_type": 18
                        }
                    ],
                    "force_fields": [
                        {
                            "entity_id": 15,
                            "type": 1
                        }
                    ],
                    "portals": [
                        {
                            "entity_id": 2,
                            "target_index": 2,
                            "entity_file_name": "Unit2_TP1_Ent"
                        },
                        {
                            "entity_id": 7,
                            "target_index": 10,
                            "entity_file_name": "unit2_RM4_Ent"
                        },
                        {
                            "entity_id": 38,
                            "target_index": 20,
                            "entity_file_name": "unit2_Land_Ent"
                        }
                    ]
                },
                "Tetra Vista": {
                    "pickups": [],
                    "force_fields": [],
                    "portals": [
                        {
                            "entity_id": 1,
                            "target_index": 31,
                            "entity_file_name": "unit2_RM7_Ent"
                        }
                    ]
                },
                "New Arrival Registration": {
                    "pickups": [
                        {
                            "entity_id": 19,
                            "entity_type": 17,
                            "model_id": 2,
                            "artifact_id": 2
                        },
                        {
                            "entity_id": 21,
                            "entity_type": 17,
                            "model_id": 0,
                            "artifact_id": 1
                        }
                    ],
                    "force_fields": [],
                    "portals": [
                        {
                            "entity_id": 24,
                            "target_index": 3,
                            "entity_file_name": "Unit2_TP2_Ent"
                        },
                        {
                            "entity_id": 41,
                            "target_index": 21,
                            "entity_file_name": "unit2_Land_Ent"
                        }
                    ]
                },
                "Celestial Gateway": {
                    "pickups": [
                        {
                            "entity_id": 21,
                            "entity_type": 17,
                            "model_id": 5,
                            "artifact_id": 2
                        }
                    ],
                    "force_fields": [
                        {
                            "entity_id": 20,
                            "type": 3
                        }
                    ],
                    "portals": [
                        {
                            "entity_id": 15,
                            "target_index": 20,
                            "entity_file_name": "unit2_C4_Ent"
                        },
                        {
                            "entity_id": 16,
                            "target_index": 21,
                            "entity_file_name": "unit2_C7_Ent"
                        }
                    ]
                },
                "Data Shrine 01": {
                    "pickups": [
                        {
                            "entity_id": 2,
                            "entity_type": 4,
                            "item_type": 4
                        },
                        {
                            "entity_id": 14,
                            "entity_type": 4,
                            "item_type": 18
                        }
                    ],
                    "force_fields": [],
                    "portals": []
                },
                "Data Shrine 02": {
                    "pickups": [
                        {
                            "entity_id": 14,
                            "entity_type": 4,
                            "item_type": 6
                        },
                        {
                            "entity_id": 18,
                            "entity_type": 4,
                            "item_type": 18
                        },
                        {
                            "entity_id": 41,
                            "entity_type": 4,
                            "item_type": 5
                        }
                    ],
                    "force_fields": [],
                    "portals": []
                },
                "Data Shrine 03": {
                    "pickups": [
                        {
                            "entity_id": 2,
                            "entity_type": 4,
                            "item_type": 4
                        }
                    ],
                    "force_fields": [],
                    "portals": []
                },
                "Transfer Lock": {
                    "pickups": [
                        {
                            "entity_id": 64,
                            "entity_type": 4,
                            "item_type": 6
                        }
                    ],
                    "force_fields": [],
                    "portals": [
                        {
                            "entity_id": 3,
                            "target_index": 10,
                            "entity_file_name": "unit2_C4_Ent"
                        },
                        {
                            "entity_id": 15,
                            "target_index": 12,
                            "entity_file_name": "unit2_RM8_Ent"
                        }
                    ]
                },
                "Incubation Vault 01": {
                    "pickups": [
                        {
                            "entity_id": 10,
                            "entity_type": 17,
                            "model_id": 1,
                            "artifact_id": 0
                        }
                    ],
                    "force_fields": [
                        {
                            "entity_id": 4,
                            "type": 7
                        }
                    ],
                    "portals": [
                        {
                            "entity_id": 2,
                            "target_index": 50,
                            "entity_file_name": "unit2_RM8_Ent"
                        },
                        {
                            "entity_id": 3,
                            "target_index": 26,
                            "entity_file_name": "unit2_RM6_Ent"
                        },
                        {
                            "entity_id": 7,
                            "target_index": 19,
                            "entity_file_name": "unit2_RM5_Ent"
                        },
                        {
                            "entity_id": 9,
                            "target_index": 18,
                            "entity_file_name": "unit2_RM5_Ent"
                        },
                        {
